/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica1_interfaces;

/**
 *
 * @author Ismael
 */
public class addAnimals extends javax.swing.JFrame {

    /**
     * Creates new form addAnimals
     */
    
    
    
    public addAnimals() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capa0 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbGuardarAnimal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtEspecieAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtRazaAnimal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPesoAnimal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNombreAnimal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Animal");

        jbGuardarAnimal.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jbGuardarAnimal.setText("Guardar");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setText("Especie");

        jtEspecieAnimal.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtEspecieAnimal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtEspecieAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEspecieAnimalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setText("Raza");

        jtRazaAnimal.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtRazaAnimal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtRazaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRazaAnimalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Peso Kg");

        jtPesoAnimal.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtPesoAnimal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtPesoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesoAnimalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel5.setText("Nombre");

        jtNombreAnimal.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtNombreAnimal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtNombreAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout capa0Layout = new javax.swing.GroupLayout(capa0);
        capa0.setLayout(capa0Layout);
        capa0Layout.setHorizontalGroup(
            capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(capa0Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jbGuardarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(capa0Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(82, 82, 82)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtRazaAnimal)
                        .addComponent(jtNombreAnimal)
                        .addComponent(jtEspecieAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                        .addComponent(jtPesoAnimal))
                    .addGap(45, 45, 45)))
        );
        capa0Layout.setVerticalGroup(
            capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capa0Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(jbGuardarAnimal)
                .addGap(39, 39, 39))
            .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(capa0Layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtEspecieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(44, 44, 44)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtRazaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtPesoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtNombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEspecieAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEspecieAnimalActionPerformed
        
    }//GEN-LAST:event_jtEspecieAnimalActionPerformed

    private void jtRazaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRazaAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRazaAnimalActionPerformed

    private void jtPesoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesoAnimalActionPerformed

    private void jtNombreAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAnimals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel capa0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbGuardarAnimal;
    private javax.swing.JTextField jtEspecieAnimal;
    private javax.swing.JTextField jtNombreAnimal;
    private javax.swing.JTextField jtPesoAnimal;
    private javax.swing.JTextField jtRazaAnimal;
    // End of variables declaration//GEN-END:variables
}
