/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica1_interfaces;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael
 */
public class addCuidados extends javax.swing.JFrame {

    ArrayList<Cuidados> cuidados;

    /**
     * Creates new form addCuidados
     */
    public addCuidados() {
        initComponents();
        cuidados = new ArrayList<Cuidados>();//array list para guardar cada objeto en una posición

    }

    //método para abrir el fichero
    public void rellenaAnimals() {
        try {
            FileInputStream fis = new FileInputStream("Animals.dat");//variable para el archivo
            ObjectInputStream inputFile = new ObjectInputStream(fis);//creamos inputFile para meter datos en el fichero
            boolean finalFichero = false;
            while (!finalFichero) {
                try {
                    cuidados.add((Cuidados) inputFile.readObject());

                } catch (EOFException e) {//excepción para final de fichero y con el boolean hacemos que salga del buche
                    finalFichero = true;
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(addCuidados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fis.close();
            inputFile.close();

        } catch (IOException f) {
            JOptionPane.showMessageDialog(null, f.getMessage());

        }

    }

    public void saveCare() {

        try {
            FileOutputStream fos = new FileOutputStream("Animals.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(fos);
            for (int i = 0; i < cuidados.size(); i++) {
                outputFile.writeObject(cuidados.get(i));
            }
            outputFile.close();
            fos.close();
            JOptionPane.showMessageDialog(null, "Guardado Correctamente");
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addCuidados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(addCuidados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void borraTodo() {

        //vacia los campo textfield
        jtCantidaComida.setText("");
        jtCostePromedio.setText("");
        jtHabitat.setText("");
        jtPeriocidadComida.setText("");
        jtTipoComida.setText("");

    }

    public void newCare() {

        //variables para guardar los datos de los textfields      
        String tipoComida = jtTipoComida.getText();

        String habitat = jtHabitat.getText();

        float costeProm = Float.parseFloat(jtCostePromedio.getText());

        float cantidadComida = Float.parseFloat(jtCantidaComida.getText());

        int pericidadComida = Integer.parseInt(jtPeriocidadComida.getText());

        Cuidados a = new Cuidados(tipoComida, habitat, costeProm, cantidadComida, pericidadComida); //creamos un paciente nuevo con los datos de las variables

        //lo guardamos en una arraylist
        cuidados.add(a);
        saveCare();//guardado automático

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtTipoComida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtHabitat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtCostePromedio = new javax.swing.JTextField();
        jbGuardarAnadirCuidados = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtCantidaComida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtPeriocidadComida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Cuidados");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setText("Tipo Comida");

        jtTipoComida.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtTipoComida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setText("Hábitat");

        jtHabitat.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtHabitat.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel4.setText("Coste Promedio");

        jtCostePromedio.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtCostePromedio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jbGuardarAnadirCuidados.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jbGuardarAnadirCuidados.setText("Guardar");
        jbGuardarAnadirCuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarAnadirCuidadosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel5.setText("Cantidad Comida KG");

        jtCantidaComida.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtCantidaComida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel6.setText("Periocidad Comida");

        jtPeriocidadComida.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jtPeriocidadComida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(125, 125, 125))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCostePromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(jtHabitat)
                    .addComponent(jtTipoComida)
                    .addComponent(jtCantidaComida)
                    .addComponent(jtPeriocidadComida))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGuardarAnadirCuidados)
                .addGap(382, 382, 382))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtTipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtCostePromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCantidaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPeriocidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(71, 71, 71)
                .addComponent(jbGuardarAnadirCuidados)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarAnadirCuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarAnadirCuidadosActionPerformed
        newCare();
        this.dispose();
    }//GEN-LAST:event_jbGuardarAnadirCuidadosActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCuidados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardarAnadirCuidados;
    private javax.swing.JTextField jtCantidaComida;
    private javax.swing.JTextField jtCostePromedio;
    private javax.swing.JTextField jtHabitat;
    private javax.swing.JTextField jtPeriocidadComida;
    private javax.swing.JTextField jtTipoComida;
    // End of variables declaration//GEN-END:variables
}
